import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import WagmiConfig et le client Wagmi
import { WagmiConfig } from "wagmi";
import { wagmiClient } from "@/lib/wagmi"; // Assurez-vous que le chemin est correct

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {WagmiConfig}
      <WagmiConfig client={wagmiClient}>
        {            children           }
      </WagmiConfig>
      </body>
      </html>
  );
}
